### PR TITLE
Fix existing tests, added tests for spoilers, and adjusted spoiler logic

### PR DESCRIPTION
**Pull request by hjiangsu**
This PR contains the following changes:
- Fixed all existing tests that were failing
- Added some spoiler tests for formatting to markdown, and widget tests
- Adjusted some of the logic for how spoilers are created. This is to allow inline selection of content to create spoilers
  - Additionally, I've adjusted to cursor positioning so that the cursor lands at the end of the spoiler body

https://github.com/thunder-app/markdown-editor/assets/30667958/580aef1d-b95d-4c69-a318-65514b69f84b

### CODE REVIEW

**Review by micahmo — APPROVED** [review]
LGTM!

> *  Adjusted some of the logic for how spoilers are created. This is to allow inline selection of content to create spoilers
>     * Additionally, I've adjusted to cursor positioning so that the cursor lands at the end of the spoiler body

Just curious, but was there a regression? Looking back at the demo in #6 both of these things worked.

**Comment by hjiangsu** [comment]
> Just curious, but was there a regression? Looking back at the demo in https://github.com/thunder-app/markdown-editor/pull/6 both of these things worked.

> selection of content to create spoilers

For this, I believe it was creating the spoiler on the same line which would be invalid!

```
This is some text ::: spoiler Spoiler
spoiler body
:::
```

The correct behaviour should be

```
This is some text
::: spoiler Spoiler
spoiler body
:::
```

> cursor positioning so that the cursor lands at the end of the spoiler body

Trying this again, I cant reproduce my issue. However, I encountered a case previously where it was not inserting the cursor at the right location (it seems like it had something to do with `selectedText` being an empty string)

**Comment by hjiangsu** [comment]
I also added a commit which fixes a couple more edge cases that I found!


https://github.com/thunder-app/markdown-editor/assets/30667958/41bc6264-fddd-4ab6-a99c-d76453d81bda

**Comment by micahmo** [comment]
Cool, thanks! Looks good!

**Pull request merged**
