### PR TITLE
Add markdown buttons for mentions

### PR DESCRIPTION
**Pull request by micahmo**
This PR adds two new actions to the set of available markdown buttons, plus the ability to define custom tap handlers. See thunder-app/thunder#751 for more info.

### CODE REVIEW

**Review by hjiangsu — COMMENTED** [review]
Looks good to me! Just a couple of minor things for icons with the new actions: right now, if I'm not mistaken, they are the `@` symbol for mentions and `!` for communities?

Would it be better if we change those to be a person icon for user and the people icon for communities? I think the person icon makes sense since we use that within Thunder already so there's an association there. I'm up to debate on the community icon though!

**Comment by micahmo** [comment]
@hjiangsu Good question. I went with `@` and `!` because those are the symbols you'd type in the web interface to trigger autocomplete suggestions. 

https://github.com/thunder-app/markdown-editor/assets/7417301/d6e2d9c6-c7e1-454e-97c6-667610075333

I agree that we use the person/people icons to generally refer to users/communities throughout the app. But I thought within the context of the post editor, these textual symbols might have a quicker subconscious association for the actions that they imply. In other words, while those other symbols are used to access/view entities, these symbols are standard across Lemmy for initiating mentions. But I may be way off here in terms of how people will interpret these!

Should we hear from some other members of the community, or are you pretty sure you want me to change the icons? Just let me know!

**Comment by hjiangsu** [comment]
Hmm, I still personally like the person/people icons for them but maybe @machinaeZER0 can provide some input on this!

**Comment by machinaeZER0** [comment]
Oh hi! :)

I actually think the @ and ! are quite clever, and the @ in particular I'd definitely keep (unless there's a conflict I'm not thinking of) - @ is used for user pings in a lot of apps so I think it's perfect for this situation!

I could see some potential confusion on the !, so I could go either way on that one. Even though I like it, it may make the most sense to change that to an icon that's more descriptive, as @hjiangsu suggested, especially since at this point we won't yet have the functionality to tag communities by typing out an exclamation point. It's also probably a bit easier to parse at a glance for someone new to Lemmy. Just my two cents!

**Comment by hjiangsu** [comment]
Yeah, my main concern with the icons is that someone new to lemmy won't fully understand what they mean at first glance. I thin @machinaeZER0 makes a good point with the `@` for mentioning a person so I'm okay with leaving that as is! But maybe we can figure out a more beginner-friendly icon for linking communities?

**Comment by machinaeZER0** [comment]
If I understood your suggestion right, I could definitely see using a version of the icon we're using for subscribers count on the community banners? Two overlapping user icons?

**Comment by hjiangsu** [comment]
I was thinking either that or the icon that we're using already for visiting community!

image

**Comment by machinaeZER0** [comment]
Ahh, right right. I think whichever works best at the size it would need to be scaled down (if necessary) would be good here - @micahmo what do you think?

**Comment by micahmo** [comment]
Thanks for the good discourse! Usually the more people that have input, the better the result.

I hear that there's some support for the `@`, but not at all for the `!`. In my opinion, it would be even more confusing to mix metaphors and have `@` for users and the community icon for communities. I think if we don't like the textual symbols, then we should lean into the icon representations.

How does this look?

| image |
| - |

**Comment by machinaeZER0** [comment]
I guess for me it feels like the @ symbol is rather universal, so it's leaves less to the imagination in my opinion. That said, while I like the idea of @ and ! (especially once those are both able to be recognized through naturally typing), I don't mind the mockup icons!

One thing I'm noticing is that our formatting bar doesn't show tooltips on a long press, which I think would be a huge help for anyone getting used to our markdown shorthand. Paired with a descriptive popup, I'd be fine with any combination of the icons proposed this far :)

**Comment by micahmo** [comment]
> our formatting bar doesn't show tooltips

I agree, this would be a big help! Just as a technical note, the markdown buttons come from a package (this repo), while the localization is done at the application level. So it would be a bit of work (but hardly impossible) to add tooltips here. Definitely a separate task.

**Comment by micahmo** [comment]
Need a final call from you @hjiangsu 😊

**Comment by hjiangsu** [comment]
Hmmm, alright maybe I'll revert back and we can just use the `@` and `!` symbols for the icons. It might take some getting used to for new users, but it makes sense overall once they learn the syntax.

@micahmo let me know if the PR is good to go!

**Comment by machinaeZER0** [comment]
And again, eventually if/when we can add tooltips to the markdown editor, it should be even more clear! I think this is the right way to go :) good discussion!

**Comment by micahmo** [comment]
Sounds good! I reverted the icons, and this PR should be good to go now!

| image |
| - |

**Pull request merged**
